# -*- coding: utf-8 -*-
"""latihan-00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWE040MCyU-KpAF_3LnV9CGT1RF-kL4_
"""

# Febilah Purtin
# A11.2022.14209
# A11.4410

# Highlight this cell and click [Shift+Enter] to execute
print('This is just a simple print statement')

import IPython
app = IPython.Application.instance()
app.kernel.do_shutdown(True)