# -*- coding: utf-8 -*-
"""latihan_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-ThDP7kF7H-YYxdQJnuWxiG-3PrcFTS
"""

# FEBILAH PURTIN
# A11.2022.14209
# A11.4410

# import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Import dataset
dataset = pd.read_csv('Churn_Modelling.csv')

# Mengambil fitur dan variabel tergantung
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# mencetak DataFrame
dataset

print(X)

print(y)

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

# melakukan encoding pada data kategorikal dalam X.
# LabelEndocoder digunakan untuk mengonversi nilai2 kategorikal bilangan bulat
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

# onehotencoder digunakan untuk mengonversi variabel kategorikal menjadi bentuk biner
onehotencoder = ColumnTransformer([('one_hot_encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = onehotencoder.fit_transform(X)
X = X[:, 1:]

print(X)

# membagi dataset menjadi Training set dan Test set dengan proporsi 80:20
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling pada fitur-fitur dalam dataset
# digunakan untuk menjaga skala fitur agar sebanding dan memudahkan proses pelatihan model
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""Now let's make the ANN!"""

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Menambahkan input layer dan hidden layer pertama
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Menambahkan hidden layer kedua
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Menambahkan output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
# epochs awal 20, kemudian di ganti menjadi 100
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

"""Making predictions and evaluating the model"""

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred_ = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_)

cm

y_test

y_pred_

y_pred

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred_)
print("Confusion Matrix:\n", cm)

# Menghitung metrik performa
accuracy = accuracy_score(y_test, y_pred_)
precision = precision_score(y_test, y_pred_)
recall = recall_score(y_test, y_pred_)
f1 = f1_score(y_test, y_pred_)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

